### ISSUE TITLE
Using "hmac_*" causes 0x to be prefixed.

### ISSUE THREAD

**Issue by freshteapot** [varnish/libvmod-digest#22] opened 2017-01-20 12:45 UTC
When hashing, the hash is prefixed with "0x".

```
digest.hmac_sha256("slssecret",req.http.host + req.url );
```

Which is not the same as when you run the equivalent in other language / programs.

Reference
- [On zendesk 14131](https://varnish.zendesk.com/agent/tickets/14131)

**Comment by rezan** [comment] 2017-01-20 21:48
This is by design as the hashes being returned are hexadecimal string representations of binary data.

You can regsub it out:

```vcl
regsub(digest.hmac_sha256("slssecret",req.http.host + req.url ), "^0x", "");
```

**Comment by daghf** [comment] 2017-01-23 14:17
Hi

The decision to prepend `0x` for hexadecimal representation was taken over five years ago, and we certainly can't change it at this point.

@rezan has pointed out a simple workaround - I'm closing this.

**Closed by daghf** 2017-01-23 14:17 UTC
